[misc] fix: make the assert user-friendly for `get_tensordict` (#5735)
### What does this PR do?

This PR adds the missing assert message.

Before:

```
  File "verl/utils/tensordict_utils.py", line 374, in get_tensordict
    assert isinstance(val, torch.Tensor | list)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```
the user has no idea which `key` is the problem, and what type the `val`
has

After:

```
    assert isinstance(val, torch.Tensor | list), f"{key} -> {type(val)} isn't of 'torch.Tensor | list' type"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: log_probs -> <class 'NoneType'> isn't of 'torch.Tensor | list' type
```
now the user knows how to fix the issue, as both the `key` is known and
the type of the value.